<?xml version="1.0"?>
<robot name="BERT2_robot" xmlns:xacro="http://www.ros.org/wiki/xacro">

    <!-- Constants for robot dimensions -->
    <xacro:property name="PI" value="3.1415926535897931"/>

    <xacro:property name="link1_mass" value="2.35" />
    <xacro:property name="link2_mass" value="3.0" />
    <xacro:property name="link1_radius" value="0.05" />
    <xacro:property name="link2_radius" value="0.05" />
    <xacro:property name="link1_length" value="0.2735" />
    <xacro:property name="link2_length" value="0.44" />
    <xacro:property name="mass" value="5" />
    <xacro:property name="axel_offset" value="0.025" /> <!-- Space btw top of beam and the each joint -->

    <xacro:property name="width" value="0.1" /> <!-- Square dimensions (widthxwidth) of beams -->
    <xacro:property name="height1" value="2" /> <!-- Link 1 -->
    <xacro:property name="height2" value="1" /> <!-- Link 2 -->
    <xacro:property name="height3" value="1" /> <!-- Link 3 -->    

    <!-- Make the robot's base immovable -->
    <link name="world"/>
    <joint name="fixed" type="fixed">
        <parent link="world"/>
        <child link="BERT2_baselink"/>
    </joint>

    <!-- Base Link -->
    <link name="BERT2_baselink">
        <collision>
            <origin xyz="0 0 ${height1/2}" rpy="0 0 0"/>
            <geometry>
                <box size="${width} ${width} ${height1}"/>
            </geometry>
        </collision>
        <visual>
            <origin xyz="0 0 ${height1/2}" rpy="0 0 0"/>
            <geometry>
                <box size="${width} ${width} ${height1}"/>
            </geometry>
            <material name="black"/>
        </visual>
        <inertial>
            <origin xyz="0 0 ${height1/2}" rpy="0 0 0"/>
            <mass value="${mass}"/>
            <inertia
                ixx="${mass / 12.0 * (width*width + height1*height1)}" ixy="0.0" ixz="0.0"
                iyy="${mass / 12.0 * (height1*height1 + width*width)}" iyz="0.0"
                izz="${mass / 12.0 * (width*width + width*width)}"/>
        </inertial>
    </link>

    <joint name="BERT2_joint1" type="continuous">
        <parent link="BERT2_baselink"/>
        <child link="BERT2_link1"/>
        <origin xyz="0 ${link1_radius*2} ${height1 - axel_offset}" rpy="0 0 0"/>
        <axis xyz="0 1 0"/>
        <dynamics damping="0.7"/>
    </joint>

    <!-- Middle Link -->
    <link name="BERT2_link1">
        <collision>
            <origin xyz="0 0 ${link1_length/2 - axel_offset}" rpy="0 0 0"/>
            <geometry>
                <cylinder radius="${link1_radius}" length="${link1_length}"/>
            </geometry>
        </collision>

        <visual>
            <origin xyz="0 0 ${link1_length/2 - axel_offset}" rpy="0 0 0"/>
            <geometry>
                <cylinder radius="${link1_radius}" length="${link1_length}"/>
            </geometry>
            <material name="grey"/>
        </visual>

        <inertial>
            <origin xyz="0 0 ${link1_length/2 - axel_offset}" rpy="0 0 0"/>
            <mass value="${link1_mass}"/>
            <inertia
                ixx="${link1_mass / 12.0 * (3*link1_radius*link1_radius + link1_length*link1_length)}" ixy="0.0" ixz="0.0"
                iyy="${link1_mass / 12.0 * (3*link1_radius*link1_radius + link1_length*link1_length)}" iyz="0.0"
                izz="${link1_mass / 2.0 * (link1_radius*link1_radius)}"/>
        </inertial>
    </link>

    <joint name="BERT2_joint2" type="continuous">
        <parent link="BERT2_link1"/>
        <child link="BERT2_link2"/>
        <origin xyz="0 ${link2_radius*2} ${link1_length - axel_offset*2}" rpy="0 0 0"/>
        <axis xyz="0 1 0"/>
        <dynamics damping="0.7"/>
    </joint>

    <!-- Top Link -->
    <link name="BERT2_link2">
        <collision>
            <origin xyz="0 0 ${link2_length/2 - axel_offset}" rpy="0 0 0"/>
            <geometry>
                <cylinder radius="${link2_radius}" length="${link2_length}"/>
            </geometry>
        </collision>

        <visual>
            <origin xyz="0 0 ${link2_length/2 - axel_offset}" rpy="0 0 0"/>
            <geometry>
                <cylinder radius="${link2_radius}" length="${link2_length}"/>
            </geometry>
            <material name="black"/>
        </visual>

        <inertial>
            <origin xyz="0 0 ${link2_length/2 - axel_offset}" rpy="0 0 0"/>
            <mass value="${link2_mass}"/>
            <inertia
                ixx="${link2_mass / 12.0 * (3*link2_radius*link2_radius + link2_length*link2_length)}" ixy="0.0" ixz="0.0"
                iyy="${link2_mass / 12.0 * (3*link2_radius*link2_radius + link2_length*link2_length)}" iyz="0.0"
                izz="${link2_mass / 2.0 * (link2_radius*link2_radius)}"/>
        </inertial>
    </link>

    <!-- Transmissions -->
    <transmission name="BERT2_tran1">
        <type>transmission_interface/SimpleTransmission</type>
        <joint name="BERT2_joint1">
            <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
        </joint>
        <actuator name="BERT2_motor1">
        <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
        <mechanicalReduction>1</mechanicalReduction>
        </actuator>
    </transmission>

    <transmission name="BERT2_tran2">
        <type>transmission_interface/SimpleTransmission</type>
        <joint name="BERT2_joint2">
            <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
        </joint>
        <actuator name="BERT2_motor2">
            <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
            <mechanicalReduction>1</mechanicalReduction>
        </actuator>
    </transmission>

    <!-- Gazebo Plugins -->
    <gazebo>
        <plugin name="gazebo_ros_control" filename="libgazebo_ros_control.so">
            <robotNamespace>/BERT2_robot</robotNamespace>
            <robotSimType>gazebo_ros_control/DefaultRobotHWSim</robotSimType>
            <controlPeriod>0.01</controlPeriod>
        </plugin>
    </gazebo>

    <!-- Additional Configs -->
    <gazebo reference="BERT2_baselink">
        <material>Gazebo/Black</material>
    </gazebo>
    <gazebo reference="BERT2_link1">
        <mu1>0.2</mu1>
        <mu2>0.2</mu2>
        <material>Gazebo/Grey</material>
    </gazebo>
    <gazebo reference="BERT2_link2">
        <mu1>0.2</mu1>
        <mu2>0.2</mu2>
        <material>Gazebo/Black</material>
    </gazebo>

</robot>