<?xml version="1.0"?>
<robot name="BERT2_robot" xmlns:xacro="http://www.ros.org/wiki/xacro">

    <!-- Constants for robot dimensions -->
    <xacro:property name="PI" value="3.1415926535897931"/>
    <xacro:property name="link1_mass" value="2.35" />
    <xacro:property name="link2_mass" value="3.0" />
    <xacro:property name="width" value="0.1" /> <!-- Square dimensions (widthxwidth) of beams -->
    <xacro:property name="height1" value="2" /> <!-- Link 1 -->
    <xacro:property name="height2" value="1" /> <!-- Link 2 -->
    <xacro:property name="height3" value="1" /> <!-- Link 3 -->
    <xacro:property name="axel_offset" value="0.05" /> <!-- Space btw top of beam and the each joint -->

    <!-- Make the robot's base immovable -->
    <link name="world"/>
    <joint name="fixed" type="fixed">
        <parent link="world"/>
        <child link="BERT2_link1"/>
    </joint>

    <!-- Base Link -->
    <link name="BERT2_link1">
        <collision>
            <origin xyz="0 0 ${height1/2}" rpy="0 0 0"/>
            <geometry>
                <box size="${width} ${width} ${height1}"/>
            </geometry>
        </collision>
        <visual>
            <origin xyz="0 0 ${height1/2}" rpy="0 0 0"/>
            <geometry>
                <box size="${width} ${width} ${height1}"/>
            </geometry>
            <material name="black"/>
        </visual>
        <inertial>
            <origin xyz="0 0 ${height1/2}" rpy="0 0 0"/>
            <link1_mass value="${link1_mass}"/>
            <inertia
                ixx="${link1_mass / 12.0 * (width*width + height1*height1)}" ixy="0.0" ixz="0.0"
                iyy="${link1_mass / 12.0 * (height1*height1 + width*width)}" iyz="0.0"
                izz="${link1_mass / 12.0 * (width*width + width*width)}"/>
        </inertial>
    </link>

    <joint name="BERT2_joint1" type="continuous">
        <parent link="BERT2_link1"/>
        <child link="BERT2_link2"/>
        <origin xyz="0 ${width} ${height1 - axel_offset}" rpy="0 0 0"/>
        <axis xyz="0 1 0"/>
        <dynamics damping="0.7"/>
    </joint>

    <!-- Middle Link -->
    <link name="BERT2_link2">
        <collision>
            <origin xyz="0 0 ${height2/2 - axel_offset}" rpy="0 0 0"/>
            <geometry>
                <box size="${width} ${width} ${height2}"/>
            </geometry>
        </collision>

        <visual>
            <origin xyz="0 0 ${height2/2 - axel_offset}" rpy="0 0 0"/>
            <geometry>
                <box size="${width} ${width} ${height2}"/>
            </geometry>
            <material name="grey"/>
        </visual>

        <inertial>
            <origin xyz="0 0 ${height2/2 - axel_offset}" rpy="0 0 0"/>
            <link1_mass value="${link1_mass}"/>
            <inertia
                ixx="${link1_mass / 12.0 * (width*width + height2*height2)}" ixy="0.0" ixz="0.0"
                iyy="${link1_mass / 12.0 * (height2*height2 + width*width)}" iyz="0.0"
                izz="${link1_mass / 12.0 * (width*width + width*width)}"/>
        </inertial>
    </link>

    <joint name="BERT2_joint2" type="continuous">
        <parent link="BERT2_link2"/>
        <child link="BERT2_link3"/>
        <origin xyz="0 ${width} ${height2 - axel_offset*2}" rpy="0 0 0"/>
        <axis xyz="0 1 0"/>
        <dynamics damping="0.7"/>
    </joint>

    <!-- Top Link -->
    <link name="BERT2_link3">
        <collision>
            <origin xyz="0 0 ${height3/2 - axel_offset}" rpy="0 0 0"/>
            <geometry>
                <box size="${width} ${width} ${height3}"/>
            </geometry>
        </collision>

        <visual>
            <origin xyz="0 0 ${height3/2 - axel_offset}" rpy="0 0 0"/>
            <geometry>
                <box size="${width} ${width} ${height3}"/>
            </geometry>
            <material name="black"/>
        </visual>

        <inertial>
            <origin xyz="0 0 ${height3/2 - axel_offset}" rpy="0 0 0"/>
            <link1_mass value="${link1_mass}"/>
            <inertia
                ixx="${link1_mass / 12.0 * (width*width + height3*height3)}" ixy="0.0" ixz="0.0"
                iyy="${link1_mass / 12.0 * (height3*height3 + width*width)}" iyz="0.0"
                izz="${link1_mass / 12.0 * (width*width + width*width)}"/>
        </inertial>
    </link>

    <!-- Transmissions -->
    <transmission name="BERT2_tran1">
        <type>transmission_interface/SimpleTransmission</type>
        <joint name="BERT2_joint1">
            <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
        </joint>
        <actuator name="BERT2_motor1">
        <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
        <mechanicalReduction>1</mechanicalReduction>
        </actuator>
    </transmission>

    <transmission name="BERT2_tran2">
        <type>transmission_interface/SimpleTransmission</type>
        <joint name="BERT2_joint2">
            <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
        </joint>
        <actuator name="BERT2_motor2">
            <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
            <mechanicalReduction>1</mechanicalReduction>
        </actuator>
    </transmission>

    <!-- Gazebo Plugins -->
    <gazebo>
        <plugin name="gazebo_ros_control" filename="libgazebo_ros_control.so">
            <robotNamespace>/BERT2_robot</robotNamespace>
            <robotSimType>gazebo_ros_control/DefaultRobotHWSim</robotSimType>
            <controlPeriod>0.01</controlPeriod>
        </plugin>
    </gazebo>

    <!-- Additional Configs -->
    <gazebo reference="BERT2_link1">
        <material>Gazebo/Black</material>
    </gazebo>
    <gazebo reference="BERT2_link2">
        <mu1>0.2</mu1>
        <mu2>0.2</mu2>
        <material>Gazebo/Grey</material>
    </gazebo>
    <gazebo reference="BERT2_link3">
        <mu1>0.2</mu1>
        <mu2>0.2</mu2>
        <material>Gazebo/Black</material>
    </gazebo>

</robot>