BERT2_robot:
  # Publish all joint states -----------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 100
  
  # Position Controller -----------
  BERT2_joint_controller:
    type: novel_adaptive_controller_paper/NovelAdaptiveControllerPaper
    joints: 
      - BERT2_joint1
      - BERT2_joint2
    gains:
      Kr: 0.5
      Kv: 1.5
      Kp: 1.5
      Kgamma: 2
      Kfilt: 100
      Kff: 0.01
      Kinit: 0.001
      Komega1: 0.002
      Komega2: 0.1