BERT2_robot:
  # Publish all joint states -----------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 100
  
  # Position Controller -----------
  BERT2_joint_controller:
    type: novel_adaptive_controller_paper/NovelAdaptiveControllerPaper
    joints: 
      - BERT2_joint1
      - BERT2_joint2
    gains:
      Kr: 5
      Kv: 15.0
      Kp: 25.0
      Kgamma: 10
      Kfilt: 1000
      Kff: 0.001
      Kinit: 0.001
      Komega1: 0
      Komega2: 0.1