planar_RR_robot:
  # Publish all joint states -----------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50
  
  # Position Controller -----------
  planar_RR_joint1_controller:
    type: my_controller/MyPositionController
    joint: planar_RR_joint1
    gain: 0.1