katana_robot:
  # Publish all joint states -----------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50
  
  # Position Controller -----------
  katana_motor2_lift_joint_controller:
    type: my_controller/MyPositionController
    joint: katana_motor2_lift_joint
    gain: 0.1